=== PaulStat/TVFreakZ/src/test/java/com/tvfreakz/repository/test.dtd
<!ELEMENT dataset (
    performer*,
    genre*,
    channels*,
    director*,
    programme*,
    episode*,
    prog_ep_perf*,
    channelprogramme*)>

<!ELEMENT channelprogramme EMPTY>
<!ATTLIST channelprogramme
    CHANNELPROGRAMMEID CDATA #REQUIRED
    CHANNELID CDATA #REQUIRED
    PROGRAMMEID CDATA #REQUIRED
    EPISODEID CDATA #REQUIRED
    RPEAT CDATA #IMPLIED
    NEWSERIES CDATA #IMPLIED
    PREMIERE CDATA #IMPLIED
    CHOICE CDATA #IMPLIED
    SUBTITLES CDATA #IMPLIED
    DEAFSIGNED CDATA #IMPLIED
    STARRATING CDATA #IMPLIED
    STARTTIME CDATA #IMPLIED
    ENDTIME CDATA #IMPLIED
    DURATION CDATA #IMPLIED
>

<!ELEMENT channels EMPTY>
<!ATTLIST channels
    CHANNELID CDATA #REQUIRED
    CHANNELNAME CDATA #IMPLIED
>

<!ELEMENT director EMPTY>
<!ATTLIST director
    DIRECTORID CDATA #REQUIRED
    DIRECTOR CDATA #IMPLIED
>

<!ELEMENT episode EMPTY>
<!ATTLIST episode
    EPISODEID CDATA #REQUIRED
    DIRECTORID CDATA #REQUIRED
    SUBTITLE CDATA #IMPLIED
    EPISODE CDATA #IMPLIED
    DESCRIPTION CDATA #IMPLIED
>

<!ELEMENT genre EMPTY>
<!ATTLIST genre
    GENREID CDATA #REQUIRED
    GENRENAME CDATA #IMPLIED
>

<!ELEMENT performer EMPTY>
<!ATTLIST performer
    PERFORMERID CDATA #REQUIRED
    PERFORMER CDATA #IMPLIED
>

<!ELEMENT prog_ep_perf EMPTY>
<!ATTLIST prog_ep_perf
    PROGRAMMEID CDATA #REQUIRED
    EPISODEID CDATA #REQUIRED
    PERFORMERID CDATA #REQUIRED
>

<!ELEMENT programme EMPTY>
<!ATTLIST programme
    PROGRAMMEID CDATA #REQUIRED
    GENREID CDATA #REQUIRED
    DIRECTORID CDATA #REQUIRED
    PROGTITLE CDATA #IMPLIED
    DESCRIPTION CDATA #IMPLIED
    YR CDATA #IMPLIED
    FILM CDATA #IMPLIED
    WIDESCREEN CDATA #IMPLIED
    BNW CDATA #IMPLIED
    CERTIFICATE CDATA #IMPLIED
>

=== PaulStat/TVFreakZ/src/test/java/com/tvfreakz/repository/testDataset.xml
<!DOCTYPE dataset SYSTEM "test.dtd">
<dataset>
    <performer PERFORMERID="1" PERFORMER="Sigourney Weaver" />
    <performer PERFORMERID="2" PERFORMER="John Hurt" />
    <performer PERFORMERID="3" PERFORMER="Bill Paxton" />
    <performer PERFORMERID="4" PERFORMER="Lance Henrikson" />
    <performer PERFORMERID="5" PERFORMER="Harrison Ford" />
    <performer PERFORMERID="6" PERFORMER="Rutger Hauer" />
	<performer PERFORMERID="7" PERFORMER="Masi Oka" />
	<performer PERFORMERID="8" PERFORMER="Hayden Panettiere" />
	<performer PERFORMERID="9" PERFORMER="Milo Ventimiglia" />
	<performer PERFORMERID="10" PERFORMER="Jack Coleman" />
	<performer PERFORMERID="11" PERFORMER="Adrian Pasdar" />
	<performer PERFORMERID="12" PERFORMER="Zachary Quinto" />
    <genre GENREID="1" GENRENAME="Arts" />
    <genre GENREID="2" GENRENAME="Childrens" />
    <genre GENREID="3" GENRENAME="Comedy" />
    <genre GENREID="4" GENRENAME="Current affairs" />
    <genre GENREID="5" GENRENAME="Documentary" />
    <genre GENREID="6" GENRENAME="Drama" />
    <genre GENREID="7" GENRENAME="Education" />
    <genre GENREID="8" GENRENAME="Entertainment" />
    <genre GENREID="9" GENRENAME="Film" />
    <genre GENREID="10" GENRENAME="Food" />
    <genre GENREID="11" GENRENAME="History" />
    <genre GENREID="12" GENRENAME="Lifestyle" />
    <genre GENREID="13" GENRENAME="Music" />
    <genre GENREID="14" GENRENAME="Nature" />
    <genre GENREID="15" GENRENAME="News" />
    <genre GENREID="16" GENRENAME="No Genre" />
    <genre GENREID="17" GENRENAME="Property" />
    <genre GENREID="18" GENRENAME="Reality" />
    <genre GENREID="19" GENRENAME="Science" />
    <genre GENREID="20" GENRENAME="Sitcom" />
    <genre GENREID="21" GENRENAME="Soap" />
    <genre GENREID="22" GENRENAME="Sport" />
    <genre GENREID="23" />
    <channels CHANNELID="92" CHANNELNAME="BBC1" />
    <channels CHANNELID="102" CHANNELNAME="BBC2" />
    <channels CHANNELID="36" CHANNELNAME="ITV" />
    <channels CHANNELID="132" CHANNELNAME="Channel 4" />
    <channels CHANNELID="134" CHANNELNAME="Channel 5" />
    <director DIRECTORID="1" DIRECTOR="Ridley Scott" />
    <director DIRECTORID="2" DIRECTOR="James Cameron" />
    <director DIRECTORID="3" DIRECTOR="David Fincher" />
    <director DIRECTORID="4" DIRECTOR="Jean-Pierre Jeunet" />
    <director DIRECTORID="5" />
    <programme PROGRAMMEID="1" GENREID="9" DIRECTORID="1" PROGTITLE="Alien" DESCRIPTION="The commercial vessel Nostromo receives a distress call from an unexplored planet. After searching for survivors, the crew heads home only to realize that a deadly bioform has joined them." YR="1979-01-01" FILM="1" WIDESCREEN="1" BNW="0" CERTIFICATE="18" />
    <programme PROGRAMMEID="2" GENREID="9" DIRECTORID="2" PROGTITLE="Aliens" DESCRIPTION="The planet from Alien (1979) has been colonized, but contact is lost. This time, the rescue team has impressive firepower, but will it be enough?" YR="1986-01-01" FILM="1" WIDESCREEN="1" BNW="0" CERTIFICATE="15" />
    <programme PROGRAMMEID="3" GENREID="9" DIRECTORID="3" PROGTITLE="Alien 3" DESCRIPTION="Ripley continues to be stalked by a savage alien, after her escape pod crashes on a prison planet." YR="1992-01-01" FILM="1" WIDESCREEN="1" BNW="0" CERTIFICATE="18" />
    <programme PROGRAMMEID="4" GENREID="9" DIRECTORID="4" PROGTITLE="Alien: Resurrection" DESCRIPTION="200 years after her death, Ellen Ripley is revived as a powerful human/Alien hybrid clone who must continue her war against the Aliens." YR="1997-01-01" FILM="1" WIDESCREEN="1" BNW="0" CERTIFICATE="18" />
    <programme PROGRAMMEID="5" GENREID="9" DIRECTORID="1" PROGTITLE="Prometheus" DESCRIPTION="Following clues to the origin of mankind a team journey across the universe and find a structure on a distant planet containing a monolithic statue of a humanoid head and stone cylinders of alien blood but they soon find they are not alone." YR="2012-01-01" FILM="1" WIDESCREEN="1" BNW="0" CERTIFICATE="15" />
    <programme PROGRAMMEID="6" GENREID="9" DIRECTORID="1" PROGTITLE="Blade Runner" DESCRIPTION="A blade runner must pursue and try to terminate four replicants who stole a ship in space and have returned to Earth to find their creator." YR="1982-01-01" FILM="1" WIDESCREEN="1" BNW="0" CERTIFICATE="15" />
    <programme PROGRAMMEID="7" GENREID="9" DIRECTORID="2" PROGTITLE="Terminator 2: Judgment Day" DESCRIPTION="A cyborg, identical to the one who failed to kill Sarah Connor, must now protect her nine-year-old son, John, from a more advanced cyborg, made out of liquid metal." YR="1991-01-01" FILM="1" WIDESCREEN="1" BNW="0" CERTIFICATE="18" />
    <programme PROGRAMMEID="8" GENREID="8" DIRECTORID="5" PROGTITLE="Heroes" DESCRIPTION="They thought they were like everyone else... until they woke with incredible abilities." YR="2006-01-01" FILM="0" WIDESCREEN="1" BNW="0" CERTIFICATE=" " />
    <episode EPISODEID="1" DIRECTORID="5" EPISODE="Chapter One 'Genesis'" DESCRIPTION="In Manhattan, Peter Petrelli is the younger brother Nathan Petrelli an overly ambitious and unscrupulous candidate for the next New York congressman, and he dreams and believes that he can fly." />
    <episode EPISODEID="2" DIRECTORID="5" EPISODE="Chapter Two 'Don't Look Back'" DESCRIPTION="When Nikki wakes up, she sees the two criminals dead in her garage. She brings her son and finds a brand new Cadillac in her name and the bodies in the trunk, with instructions and a map to bury the corpses in the desert." />
    <episode EPISODEID="3" DIRECTORID="5" EPISODE="Chapter Three 'One Giant Leap'" DESCRIPTION="Hiro gets back to Japan and using Issac's comic book he persuades Ando to help him save the world." />
    <episode EPISODEID="4" DIRECTORID="5" EPISODE="Chapter Four 'Collision'" DESCRIPTION="Hiro and Ando arrive to Vegas, where they gamble and win thanks to Hiro's powers. " />
    <episode EPISODEID="5" DIRECTORID="5" EPISODE="Chapter Five 'Hiros'" DESCRIPTION="Niki is questioned by police about her fugitive husband's whereabouts" />
    <episode EPISODEID="6" DIRECTORID="5" EPISODE="Chapter Six 'Better Halves'" DESCRIPTION="Hiro and his buddy embark on their heroic journey to New York, when they are stopped by a Vegas high-roller who offers them a deal they can't refuse." />
    <episode EPISODEID="7" DIRECTORID="5" />
    <prog_ep_perf PROGRAMMEID="1" EPISODEID="7" PERFORMERID="1" />
	<prog_ep_perf PROGRAMMEID="2" EPISODEID="7" PERFORMERID="1" />
	<prog_ep_perf PROGRAMMEID="3" EPISODEID="7" PERFORMERID="1" />
	<prog_ep_perf PROGRAMMEID="4" EPISODEID="7" PERFORMERID="1" />
	<prog_ep_perf PROGRAMMEID="1" EPISODEID="7" PERFORMERID="2" />
	<prog_ep_perf PROGRAMMEID="2" EPISODEID="7" PERFORMERID="3" />
	<prog_ep_perf PROGRAMMEID="2" EPISODEID="7" PERFORMERID="4" />
	<prog_ep_perf PROGRAMMEID="3" EPISODEID="7" PERFORMERID="4" />
	<prog_ep_perf PROGRAMMEID="6" EPISODEID="7" PERFORMERID="5" />
	<prog_ep_perf PROGRAMMEID="6" EPISODEID="7" PERFORMERID="6" />
	<prog_ep_perf PROGRAMMEID="8" EPISODEID="1" PERFORMERID="7" />
	<prog_ep_perf PROGRAMMEID="8" EPISODEID="1" PERFORMERID="8" />
	<prog_ep_perf PROGRAMMEID="8" EPISODEID="1" PERFORMERID="9" />
	<prog_ep_perf PROGRAMMEID="8" EPISODEID="1" PERFORMERID="10" />
	<prog_ep_perf PROGRAMMEID="8" EPISODEID="1" PERFORMERID="11" />
	<prog_ep_perf PROGRAMMEID="8" EPISODEID="2" PERFORMERID="7" />
	<prog_ep_perf PROGRAMMEID="8" EPISODEID="2" PERFORMERID="8" />
	<prog_ep_perf PROGRAMMEID="8" EPISODEID="2" PERFORMERID="9" />
	<prog_ep_perf PROGRAMMEID="8" EPISODEID="2" PERFORMERID="10" />
	<prog_ep_perf PROGRAMMEID="8" EPISODEID="2" PERFORMERID="11" />
	<prog_ep_perf PROGRAMMEID="8" EPISODEID="3" PERFORMERID="7" />
	<prog_ep_perf PROGRAMMEID="8" EPISODEID="3" PERFORMERID="8" />
	<prog_ep_perf PROGRAMMEID="8" EPISODEID="3" PERFORMERID="9" />
	<prog_ep_perf PROGRAMMEID="8" EPISODEID="3" PERFORMERID="10" />
	<prog_ep_perf PROGRAMMEID="8" EPISODEID="3" PERFORMERID="11" />
	<prog_ep_perf PROGRAMMEID="8" EPISODEID="4" PERFORMERID="7" />
	<prog_ep_perf PROGRAMMEID="8" EPISODEID="4" PERFORMERID="8" />
	<prog_ep_perf PROGRAMMEID="8" EPISODEID="4" PERFORMERID="9" />
	<prog_ep_perf PROGRAMMEID="8" EPISODEID="4" PERFORMERID="10" />
	<prog_ep_perf PROGRAMMEID="8" EPISODEID="4" PERFORMERID="11" />
	<prog_ep_perf PROGRAMMEID="8" EPISODEID="5" PERFORMERID="7" />
	<prog_ep_perf PROGRAMMEID="8" EPISODEID="5" PERFORMERID="8" />
	<prog_ep_perf PROGRAMMEID="8" EPISODEID="5" PERFORMERID="9" />
	<prog_ep_perf PROGRAMMEID="8" EPISODEID="5" PERFORMERID="10" />
	<prog_ep_perf PROGRAMMEID="8" EPISODEID="5" PERFORMERID="11" />
	<prog_ep_perf PROGRAMMEID="8" EPISODEID="6" PERFORMERID="7" />
	<prog_ep_perf PROGRAMMEID="8" EPISODEID="6" PERFORMERID="8" />
	<prog_ep_perf PROGRAMMEID="8" EPISODEID="6" PERFORMERID="9" />
	<prog_ep_perf PROGRAMMEID="8" EPISODEID="6" PERFORMERID="10" />
	<prog_ep_perf PROGRAMMEID="8" EPISODEID="6" PERFORMERID="11" />
	<prog_ep_perf PROGRAMMEID="8" EPISODEID="6" PERFORMERID="12" />
	<channelprogramme CHANNELPROGRAMMEID="1" CHANNELID="92" PROGRAMMEID="1" EPISODEID="7" RPEAT="1" NEWSERIES="0" PREMIERE="0" CHOICE="0" SUBTITLES="1" DEAFSIGNED="0" STARRATING="5" STARTTIME="2015-01-19 20:00:00.000000000" ENDTIME="2015-01-19 22:00:00.000000000" DURATION="120" />
	<channelprogramme CHANNELPROGRAMMEID="2" CHANNELID="92" PROGRAMMEID="1" EPISODEID="7" RPEAT="1" NEWSERIES="0" PREMIERE="0" CHOICE="0" SUBTITLES="1" DEAFSIGNED="0" STARRATING="5" STARTTIME="2015-01-26 20:00:00.000000000" ENDTIME="2015-01-26 22:00:00.000000000" DURATION="120" />
	<channelprogramme CHANNELPROGRAMMEID="3" CHANNELID="102" PROGRAMMEID="2" EPISODEID="7" RPEAT="1" NEWSERIES="0" PREMIERE="0" CHOICE="0" SUBTITLES="1" DEAFSIGNED="0" STARRATING="5" STARTTIME="2015-01-19 20:00:00.000000000" ENDTIME="2015-01-19 22:00:00.000000000" DURATION="120" />
